version: 0.4.6b{build}

branches:
  only:
  - buildmods
build:
  verbosity: minimal

environment:

  my_variable:
    secure: tKYM1oHNwH7n+FO1exDSPzz76oio0iXtsfkZ0o7kuOY=

  matrix:

    fast_finish: true

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CONFIG: Release
      PYVER: 38

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CONFIG: Release
      PYVER: 37

build_script:
  - git submodule update --init --recursive ./Dependencies/imgui
  - git submodule update --init --recursive ./Dependencies/ImGuiFileDialog
  - mkdir cmake-build-release
  - cd cmake-build-Release
  - cmake .. -G "%GENERATOR%" -A "%ARCH%" -DMVDIST_ONLY=True -DMV%PYVER%DIST=True
  - cd ..
  - cmake --build cmake-build-release --config "%CONFIG%"

on_success:
  - cd Distribution
  - call C:/Python38-x64/python.exe BuildPythonWheel.py C:/projects/dearpygui/cmake-build-release/DearPyGui/Release/core.pyd core.pyd
  - call C:/Python38-x64/python.exe -m pip install twine
  - call C:/Python38-x64/python.exe -m pip install wheel
  - call C:/Python38-x64/python.exe -m setup bdist_wheel --plat-name win_amd64 --dist-dir C:/projects/dearpygui/DearPyGui/dist
  - call C:/Python38-x64/python.exe -m twine upload --repository testpypi dist/* -u __token__ -p $(tKYM1oHNwH7n+FO1exDSPzz76oio0iXtsfkZ0o7kuOY=) --skip-existing