version: 0.4.6b{build}

branches:
  only:
  - buildmods
build:
  verbosity: minimal

environment:

  my_variable:
    secure: tKYM1oHNwH7n+FO1exDSPzz76oio0iXtsfkZ0o7kuOY=

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CONFIG: Release
      PYVER: 38
      PYLOC: "C:/Python38-x64/python.exe"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CONFIG: Release
      PYVER: 37
      PYLOC: "C:/Python37-x64/python.exe"

matrix:
  fast_finish: true

build_script:
  - git submodule update --init --recursive ./Dependencies/imgui
  - git submodule update --init --recursive ./Dependencies/ImGuiFileDialog
  - mkdir cmake-build-release
  - cd cmake-build-Release
  - cmake .. -G "%GENERATOR%" -A "%ARCH%" -DMVDIST_ONLY=True -DMVPY_VERSION=%PYVER%
  - cd ..
  - cmake --build cmake-build-release --config "%CONFIG%"

on_success:
  - cd Distribution
  - call %PYLOC% BuildPythonWheel.py C:/projects/dearpygui/cmake-build-release/DearPyGui/Release/core.pyd core.pyd
  - call %PYLOC% -m pip install twine
  - call %PYLOC% -m pip install wheel
  - call %PYLOC% -m setup bdist_wheel --plat-name win_amd64 --dist-dir C:/projects/dearpygui/dist
  - if %APPVEYOR_REPO_BRANCH%==development call %PYLOC% -m twine upload --repository testpypi C:/projects/dearpygui/dist/* -u RaylockLLC -p %my_variable% --skip-existing