name: Master Build

on:
  push:
    branches: [ master, buildmods ]
  pull_request:
    branches: [ master ]
    

jobs:

  build-windows:
    
    runs-on: windows-2019
    if: "contains(github.event.head_commit.message, 'ci run')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive
      
    - name: Build Python
      shell: cmd
      run: |
        cd Scripts
        call BuildPythonForWindows.bat --ci
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
        
    - name: Build DearPyGui
      shell: cmd
      run: |
        cmake --build cmake-build-release --config Release

  build-MacOS:
    
    runs-on: MacOS-latest
    if: "contains(github.event.head_commit.message, 'ci run')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake .. -DMVDIST_ONLY=True

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release

  build-Ubuntu:
    
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'ci run')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install xorg-dev
        cd Scripts
        chmod +x BuildPythonForLinux.sh
        ./BuildPythonForLinux.sh
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release
