name: Stable Build

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]
    
jobs:

  build-MacOS:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake .. -DMVDIST_ONLY=True

    - name: Build Dear PyGui
      run: |
        cmake --build cmake-build-release --config Release

    - name: Build Release DearPyGui Wheel
      run: |
        cd /Users/runner/work/DearPyGui/DearPyGui/Distribution
        python3 BuildPythonWheel.py /Users/runner/work/DearPyGui/DearPyGui/cmake-build-release/DearPyGui/core.so core.so
        python3 -m setup bdist_wheel --plat-name macosx-10.6-x86_64 --dist-dir /Users/runner/work/DearPyGui/DearPyGui/dist

    - name: Save Test DearPyGui Wheel
      if: "contains(github.event.head_commit.message, 'save artifact')"
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: /Users/runner/work/DearPyGui/DearPyGui/dist/*

    - name: Upload Release DearPyGui Wheel
      if: "contains(github.event.head_commit.message, 'upload run')"
      run: |
        python3 -m twine upload dist/* -u __token__ -p ${{ secrets.pypi_password }} --skip-existing

  build-MacOS37:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: |
        git submodule update --init --recursive
        cd Dependencies
        cd cpython
        git checkout v3.7.9
    
    - name: Build Python
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake .. -DMVDIST_ONLY=True -DMV37DIST=True

    - name: Build Dear PyGui
      run: |
        cmake --build cmake-build-release --config Release

    - name: Build Release DearPyGui Wheel
      run: |
        cd /Users/runner/work/DearPyGui/DearPyGui/Distribution
        python3 BuildPythonWheel.py /Users/runner/work/DearPyGui/DearPyGui/cmake-build-release/DearPyGui/core.so core.so
        python3 -m setup bdist_wheel --plat-name macosx-10.6-x86_64 --dist-dir /Users/runner/work/DearPyGui/DearPyGui/dist

    - name: Save Test DearPyGui Wheel
      if: "contains(github.event.head_commit.message, 'save artifact')"
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: /Users/runner/work/DearPyGui/DearPyGui/dist/*

    - name: Upload Release DearPyGui Wheel
      if: "contains(github.event.head_commit.message, 'upload run')"
      run: |
        python3 -m twine upload dist/* -u __token__ -p ${{ secrets.pypi_password }} --skip-existing
